# config/environments/default.yml
#
# This is the main yaml file used to store our data for some page object features.
#

google_url: https://www.google.com/
practice_url: https://codepen.io/jshlfts32/full/bjambP/